name: kickin_utilities
description: "A modular Flutter utilities package useful utilities such as constants, extensions, helpers, mixins, and state management."
version: 0.0.1+1
homepage: https://github.com/okikday/kickin_utilities
repository: https://github.com/okikday/kickin_utilities

environment:
  sdk: ^3.11.5
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
